apiVersion: v1
kind: Service
metadata:
  name: k8s-test1
spec:
  type: LoadBalancer
  selector:
    app: k8s-test1
  ports:
  - port: 9852
    targetPort: 7654
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-test1
  template:
    metadata:
      labels:
        app: k8s-test1
    spec:
      containers:
      - name: k8s-test1
        image: amks1/k8s_test:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 7654
